sudo: required

services:
  - docker

before_install: 
  - docker build -t docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker_react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-279955776817"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: "$SECRET_ACCESS_KEY"