version: '3.8'

services:
  frontend_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 8080:3000
    restart: always
  
  forntend_app_test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    command: ["npm", "run", "test"]